### ISSUE TITLE
[Data Quality] Backfill timeseries for total testing in as many states as possible

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#500]
**Target Date:** TBD
**Overview**: Fill in historicals for total PCR tests by specimens and people in all states where it is available to enable drawing directly from it for as many states as possible in our new totals column. Prefer testing encounters over unique people where both are available, but do not launch extensive investigations into testing encounters vs. people where the language is unclear.
**Contribution to Milestone**: This will enable the main goal of the milestone—providing explicit totals for every state, one by one, instead of using positive+negative. We cannot do that without having these values filled in.
**Other Benefits**: Improved historical totals.
**Potential Challenges**: It is really hard to backfill these figures and to make decisions about which kind of historical dating to use, as well as how to sync it up with our pre-existing timeseries.
Some states may provide both testing encounters and unique people historical timeseries. We should try to capture both in our historical updates, even if not in our States Daily capture.
DQ and backfill will be working on this from two different angles—backfill from the angle of our communication with that state, and DQ from the angle of our handling in worksheet2. We will need to ensure they coordinate.
We will need to perform outreach to states to clarify "Unclear" totals.
**Editorial**: None at this step. We will run the editorial content on the change when we surface it in the totals columns.

**DQ:**
- [x] Do an annotation run on Specimens vs. People for Totals, skipping questions about  encounters vs. unique people (see questions in Annotations below, which also proposes splitting SVP into three tabs, similar to recent partitioning of PCL into two tabs). 
- [ ] For each state with wrong worksheet2 handling that is not currently reporting "unclear" totals:
   - [ ] Fix worksheet2 handling
   - [ ] File GH Issue investigating the total tests history and log in a central GH issue to track our investigations in all states. 
   - [ ] Fix the issue, with assist from backfill as needed
- [ ] For any unclear totals states:
    - [ ] Reach out to them to clarify whether their totals are specimens vs people. 
    - [ ] Pass on the information from states that respond to backfill team to file GH issues.
    - [ ] For states that do not respond, stop tracking unclear totals.

**Backfill:**
- [ ] For each state, in order of priority depending on our communication with that state:
   - [ ] File GH Issue investigating the total tests history, with assist from DQ as needed, and log in a central GH issue to track our investigations in all states
   - [ ] Fix the issue by filling in the timeseries
