### ISSUE TITLE
[Data Quality] Capture current values and fill in historicals for probable cases in DE spreadsheet

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#501]
**Target Date:** 8/1
**Overview:** Start explicitly recording probable cases during daily data entry shifts and backfill historical values.
**Contribution to milestone:** This issue will enable us to expose probable cases explicitly in the API/public spreadsheet, enabling better communication when we switch to confirmed+neg instead of pos+neg.
**Other benefits:** better understanding of probables (whether they are indeed pos-confirmed)
**Potential challenges:** We are hoping that the probables equal Positives (confirmed+probable) - Positive Cases (PCR) in all states, but if this is not the case we may need to do more digging.
**Editorial:** None

- [x] Add an explicit Cases (Probable) column to worksheet2. Begin collecting it in daily DE shifts.
- [ ] Create a sanity checking spreadsheet that checks whether Positives (confirmed+probable) - Positive Cases (PCR) matches our recorded probables values
- [ ] Backfill probables by using the calculation or other backfill sources if needed. File GH issues for any complicated states.
