### ISSUE TITLE
[Data Quality] Milestone IV: Change Total Test Resuts from Calculation to Direct number

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#502]
Changing totalTestResults column to stop calculating from pos+neg and instead use a direct totals value.

- [ ] Analyze [states identified by script where there are gaps](https://docs.google.com/spreadsheets/d/1G_enjvPFG2CUAFiAGpeg-V0lKIdB6L5aDz2-GeiRrP4/edit#gid=0) in `Total Tests (PCR)` or `Total PCR Tests (People)`
- [ ] Check other states to ensure they have no gaps.
- [ ] Switch API from using pos+neg to using whichever total test figure is available.

Note: While #500 will affect the values of `Total Tests (PCR)` and `Total PCR Tests (People)`, we plan to launch this before it because of the importance of correcting the negative effects of pos+neg on data quality.
