### ISSUE TITLE
[Data Quality] Go Through State Public Notes and Annotations and Add Important Milestones to Contentful Annotations 

### ISSUE THREAD

**Issue by karaschechtman** [COVID19Tracking/issues#520]
- [ ] Create a spreadsheet to track which states' public notes we have gone through.
- [ ] Read each state's public notes and note any important dates in Contentful
- [ ] Go through PCL annotations and add important dates to Contentful
- [ ] Go through SVP Annotations and add important dates to Contentful

**Comment by muamichali** [comment]
Focus changed on this. Revamped task is tracked in Airtable
