### ISSUE TITLE
[Data Quality] Publish Confirmed/Probable Deaths to the API

### ISSUE THREAD

**Issue by karaschechtman** [COVID19Tracking/issues#566]
- [x] Revise remaining difficult states
   - [x] Backfill VA from screenshots (MM)
   - [x] Revise CO (KWS)
   - [x] Discuss MA to see if it should be revised (QN)
- [x] Add the a [list of any public notes that need to be added](https://covid-tracking.slack.com/archives/C012C4BEAR4/p1593657054040400) when we release the columns (MM/QN)
- [x] Write API Descriptions for the two new columns (MM+QN)
- [x] Write [RFC doc to publish the columns](https://docs.google.com/document/d/1uss2h94HbXsS4n5AMmjXKGfMGWmwsf3IFu81FGOgwdA/edit#) (MM)
- [x] Write draft of [blog post](https://docs.google.com/document/d/13HtVFHMoKK6zY2JCMxg_54_QpkuNAFHD3ImIjt4nUEg/edit#) to publish the columns (KWS)
- [x] Get editorial approval to launch from Erin after [explaining CO/ND](https://docs.google.com/document/d/17hQ9trz16EDtgiQ91H0__6RxiN5tXFZnyNkxcShj0RA/edit#heading=h.r91ijgqado48) highlighting the decision to use the state's confirmed numbers as confirmed  (MM+QN)
- [x] Kara to write a mini blog post about deaths until the full investigation can be done
- [x] Fix ND redux (KWS)
---

**Comment by muamichali** [comment]
@kissane This is our plan for tomorrow..

**Comment by muamichali** [comment]
@karaschechtman to make a super short description of the issue for Tuesday or Wednesday for a mini blog post we can release with the columns

**Comment by karaschechtman** [comment]
just a note that I have done the low priority updates for all except PR where we need a spanish speaker -> planning on formulating the task tomorrow

**Comment by muamichali** [comment]
I moved the post launch tasks to #592
