### ISSUE TITLE
[Data Quality] Filling in complete timeseries for confirmed cases

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#578]
**Target Date**: 08/01

**Overview**: Fill in the timeseries for positiveCasesViral in the API (also known as “Positive Cases (PCR)” on Worksheet2) to enable calculating totals with confirmed+neg instead of pos+neg.
**Contribution to Milestone**: This measure will ensure our technique of calculating totals for each state by cases+negatives does not include probable cases in our total tested counts when we can prevent it.
**Other Benefits**: This milestone will also support changing our website graphs to graph just confirmed cases rather than confirmed+probable by drawing on the backfilled confirmed field.
**Potential Challenges**:
States may not all provide sources we can backfill from, and if they do the strategies of dating cases used in those historicals may not be by date reported and therefore may not match our time-series. We will need to decide what to do.
Backfilling confirmed cases will have cascading effects requiring updates to states where we were calculating negatives by totals - lumped cases. In these cases, negatives calculation will need to be updated to totals - confirmed cases.
Before states started separating out confirmed cases, there may be discontinuities in the timeseries (e.g. the totals number may suddenly appear to drop the day we switch from using a state’s lumped numbers to confirmed ones).
**Editorial**: None for this issue. We will release editorial along with #676 

- [x] Revamp the PCL Cases spreadsheet
- [x] Checks on PCL Cases
- [x] Double Checks on PCL Cases
- [ ] Submit outreach on states with unclear PCL Cases policies and modify labels according to answers
- [ ] DQ investigates “Positive Cases (PCR)” history by investigating States Daily for historicals filing GitHub issues for any states with incomplete historical time-series 
   _Note: we accidentally began this process without DCing our labels, so we are reviewing the issues we filed before DCs._
- [ ] DQ resolves the issues, calling in backfill team for help when they are especially thorny

**Comment by muamichali** [comment]
We moved tracking of tasks like this one to Airtable. We report on any timeseries changes in Github.
