### ISSUE TITLE
[Data Quality] Create State-Tabbed Annotations Prototype

### ISSUE THREAD

**Issue by karaschechtman** [COVID19Tracking/issues#625]
- [x] Create one example state tab
   - [x] annotations
   - [x] worksheet2
   - [x] outreach
- [x] Summary tab
- [x] Definitions tab
- [ ] Worksheet2 Mappings tab
- [ ] Workshop design changes round 1
    - [ ] change units display
   -  [ ] change log
   -  [ ] refactor imports to import whole worksheet2/states matrix/outreach to tab then reference tab
- [ ] workshop design changes round 2
- [ ] Add blank tabs for all rest of states
- [ ] run configurations tab
