### ISSUE TITLE
[Data Quality] Analyse Sources of Deaths

### ISSUE THREAD

**Issue by karaschechtman** [COVID19Tracking/issues#626]
- [x] Create a spreadsheet to track Deaths Definitions
- [ ] Calculate CDC Data Tracker diffs
- [ ] Calculate NCHS diffs
- [ ] Complete Deaths Definition Collection
- [ ] Write blog post
