### ISSUE TITLE
[Data Quality] Switch to explicit totals on a state-by-state basis for states with complete timeseries

### ISSUE THREAD

**Issue by karaschechtman** [COVID19Tracking/issues#661]
**Target Date:** 08/01

**Overview:** Currently, we display our total counts by calculating it from positives and negatives. However, in some states, we already have complete time series for the totals, either specimens or people. We can start displaying those where available.

**Contribution to milestone:** This step will move us away from our stopgap measure of using cases plus negatives for states wherever it is possible already. It will therefore also improve our national testing figures. 

**Other benefits:** This will give us a chance to work on the API questions about drawing from totals rather than pos+neg ahead of time.

**Potential challenges:** It may be a technical challenge to have different standards for what we display for totals (pos+neg vs. explicit figures) in different states and to mix those different standards to create our visuals depending on the states.  We will need to communicate the change as it will result in a shift of our total test metrics.

**Editorial:** Once we figure out which states we are changing, we should put up a blog post explaining the change and making a running list of the changes.

- [ ] Figure out which states are candidates for easy backfill and total test timeseries
- [ ] For each state:
   - [ ] Verify the current Specimens vs. People annotations are correct for each state
   - [ ] Backfill the states
- [ ] Push change in total test logic away from pos+neg to explicit totals for these states to API/website
- [ ] Publish blog post.
