### ISSUE TITLE
[Data Quality] Clean our negatives

### ISSUE THREAD

**Issue by karaschechtman** [COVID19Tracking/issues#662]
**Target Date:** TBD
**Overview:** Once the totals are launched, we should delete any negatives in our capture as well as historicals that mix units between specimens and people (usually by doing total tests (specimens) - positive confirmed cases).
**Contribution to milestone:** This will undo the negative (pun absolutely intended) effects on negatives of the workaround solution we had devised for totals. 
**Other benefits:** 
**Potential challenges:** We will need to communicate why many states will no longer have negatives values and why our negatives are changing. Otherwise, this change should be pretty simple.
**Editorial:** A blog post explaining our prior method of calculating negatives.

- [ ] Go through each state and record when we are calculating negatives incorrectly. 
- [ ] Edit tooltips in worksheet2 
- [ ] File GitHub Issues to delete and investigate historical negatives to ensure the negatives were always incorrect.
- [ ] Delete historical negatives based on the GitHub issues.

**Comment by muamichali** [comment]
This task was moved to [Airtable Card](https://airtable.com/tbl78phKvQLbKQvV0/viwfU8qXN4H3pM3Rb/recACZwCzwMOhKmoU)

CC @jaclyde hi :)
