### ISSUE TITLE
[Data Quality] Switch from positives+negatives to total tests in the API and website

### ISSUE THREAD

**Issue by karaschechtman** [COVID19Tracking/issues#665]
**Target Date:** TBD
**Overview:** Start drawing from specimens, testing encounters, or people in our total tests column to display specimens and people values explicitly on the website.
**Contribution to milestone:** This will fulfill the main goal of the milestone—providing explicit totals for as many states as possible instead of using positive+negative. 
**Other benefits:** More transparency around Specimens Vs. People. 
**Potential challenges:** To aggregate a national testing number, we will need to be clear about mixing specimens and people.
**Editorial:** Public notes for each state, a blog post explaining where we are and where we are headed with testing encounters vs. people, a blog post explaining the changes overall.

- [ ] For all states that are ready, switch our total tests column to draw from explicit specimens
- [ ] Add public notes [to each state explaining our policy for it](https://trello.com/c/Ph6VrCq9/68-public-notes-changes-to-total-tests)
- [x] Post a blog post [explaining testing encounters vs. people](https://trello.com/c/JY6rf3J0/95-post-testing-encounters-are-the-new-people)
- [ ] Post a blog post explaining the [overall totals changes and what each state is drawing from](https://trello.com/c/Mt4wSEKe/102-post-final-total-tests-changes)

### States Switched Log
- [x]  Colorado 8/13
- [x] Rhode Island 8/17

**Comment by muamichali** [comment]
Remaining states tracking will be in airtable and reported via twitter and on here:
https://covidtracking.com/about-data/total-tests
