### ISSUE TITLE
[Data Quality] Release explicit probables field in spreadsheet and API

### ISSUE THREAD

**Issue by karaschechtman** [COVID19Tracking/issues#677]
**Target Date:** TBD
**Overview:** Launch the probables column.
**Contribution to milestone:** This will enable better communication when we switch to confirmed+neg instead of pos+neg.
**Other benefits:** Less inferred calculation for API users
**Potential challenges:** We are hoping that the probables equal Positives (confirmed+probable) - Positive Cases (PCR) in all states, but if this is not the case we will need to communicate to the public why.
Editorial: A tweet announcing the new column most likely

- [ ] Expose the probable cases field in the public spreadsheet
- [ ] Release probable cases in the API
- [ ] Announce the release in a Tweet
