### ISSUE TITLE
[MI] Historical Positive Cases (PCR) are sometimes higher than lumped cases, need to be corrected

### ISSUE THREAD

**Issue by karaschechtman** [COVID19Tracking/issues#701]
**State or US**: MI

**Describe the problem**
Before 4/12, the value for Positive Cases (PCR) are sometimes higher than the value for the Positives column (it appears for every day except 4/10-4/11). E.g., on 3/17 we record 4491 confirmed cases, but only 3659 lumped. This appears to be the result of a backfill on 6/11. We should fill in these values from the most recent backfill data provided by MI, making sure that Positive Cases (PCR) are allotted to the right date

**Link to data source**
usual MI spot

**Action Plan**

- [x] Backfill `Probable Cases` from 6/12 - 7/27 from total-confirmed
- [x] `Positive Cases PCR` - timeseries corrections
1. on june 9th , 59278 was duplicated on 6/9 by mistake
2. on march 17th, a number was missed
- [x] `Positive Cases (confirmed+probable)` time series                        
the number from 3/1-3/16 were not updated by 6/11 backfill by mistake                        
- [x] Backfill `Probable Cases` from 3/1-6/11 using the numbers from the file MI gave us on 6/11 (we didn't have the column yet then so we couldn't stash that anywhere)

**Comment by muamichali** [comment]
Previous Backfill GH issue https://github.com/COVID19Tracking/issues/issues/487

**Comment by muamichali** [comment]
Before and After values are in the attached sheet.
[Probable-Confirmed-Total Cases Timeseries Backfill  MI.xlsx](https://github.com/COVID19Tracking/issues/files/5272000/Probable-Confirmed-Total.Cases.Timeseries.Backfill.MI.xlsx)
