### ISSUE TITLE
Data quality checklist

### ISSUE THREAD

**Issue by hammer** [COVID19Tracking/issues#72]
We should publish to a staging sheet, wire that sheet up to the API, and run some data quality checks before publishing to the production sheet.

**Comment by hammer** [comment]
- [ ] Make sure no cumulative values go down
- [ ] Warn if increases are outside of the normal rate of increases
- [ ] Make sure no daily or current values are greater than cumulative values
- [ ] Make sure things that are supposed to sum to a number do that
- [ ] Compare across sheets (US daily vs. US current, States daily vs. States current) and highlight differences
- [ ] Warn if only one number does not change for a state (cf. https://github.com/COVID19Tracking/issues/issues/71)
- [ ] Compare county case and death sums to ours (cf. [county comparison notebook](https://github.com/COVID19Tracking/associated-data/blob/master/county_data/County%20Data%20Comparison.ipynb))

**Comment by Erin-Boehmer** [comment]
Dev starting in [quality-control repo]( https://github.com/COVID19Tracking/quality-control)

**Comment by joshuaellinger** [comment]
I've only got internal self-tests right now.  I want to work out the data flow and will get the cross data checks next.

**Comment by hammer** [comment]
@joshuaellinger sorry for the slow replies this weekend, was hanging with the fam. Awesome that you jumped on this one so quickly, I'll have more comments tomorrow (today?) when I'm back at my desk.

**Comment by joshuaellinger** [comment]
I ran it as the update was happening yesterday and make some improvements.  I want to do that against today and then I'll publish it to an HTML endpoint.  A number of states don't update tests on the weekend. 

The current ERROR results are listed below.  I have checks implemented for missing checker initials that show up as we approach 5PM.  There are a lot of little engineering judgement decisions on when to make something an error vs a warning.

=====| ERROR |===========
CA: positive value (5,708) has not changed since 03/28 (2 days)
CA: negative value (20,549) has not changed since 03/27 (3 days)
CA: death value (123) has not changed since 03/28 (2 days)
CA: total value (90,657) has not changed since 03/28 (2 days)
DE: Too many positive 85% (positive=232, total=274)
DE: positive value (232) has not changed since 03/28 (2 days)
MI: positive value (5,486) has not changed since 03/28 (2 days)
MI: negative value (11,893) has not changed since 03/28 (2 days)
MI: death value (132) has not changed since 03/28 (2 days)
MI: total value (17,379) has not changed since 03/28 (2 days)
MS: source hasn't updated in 1.7 days
MT: negative value (3,961) is less than prior value (4,143)
MT: total value (4,132) is less than prior value (4,297)
OR: positive value (548) has not changed since 03/28 (2 days)
OR: negative value (10,878) has not changed since 03/28 (2 days)
OR: total value (11,426) has not changed since 03/28 (2 days)
RI: positive value (294) has not changed since 03/28 (2 days)
