### ISSUE TITLE
[Data Quality] Correct Current and Historical Capture of Total Test column when capture does not match our understanding

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#771]
**Target Date:** 8/19
**Overview:** Review all the states where the SVP tab indicates that our ws2 capture has issues. [Full Instructions in Slack Thread](https://covid-tracking.slack.com/archives/C012C4BEAR4/p1596841835135500?thread_ts=1596841829.135400&cid=C012C4BEAR4)
**Contribution to milestone:** Correct and full time-series can be displayed on the website and the API
**Comment:** This is a meta issue we have been working on since 8/7
**Editorial:** Create GitHub issues to document changes. If need be, add a public note as well

### Current CTP Capture does not match our understanding/state reporting is unclear
- [x] MT https://github.com/COVID19Tracking/issues/issues/742
- [x] NC https://github.com/COVID19Tracking/issues/issues/759
- [x] NJ https://github.com/COVID19Tracking/issues/issues/762 
    * Until 5/11 `Total Tests PCR (People)` 
    * From 5/12 `Total Tests (PCR)`
- [x] SD https://github.com/COVID19Tracking/issues/issues/763
    * From 8/3 `Total Tests (PCR)`
    * Full time series `Total Tests PCR (People)` 
- [x] AR https://github.com/COVID19Tracking/issues/issues/748 - Unclear reporting units logged in Total Tests (PCR) (performing outreach)
- [x] GU https://github.com/COVID19Tracking/issues/issues/751 - Unclear reporting units logged in Total Tests (PCR) (performing outreach)
- [x] OH https://github.com/COVID19Tracking/issues/issues/760 - Unclear reporting units logged in Total Tests (PCR) (performing outreach)
    * Time series for `Total Tests (PCR)` through 4/20 from screenshots
- [x] PA - https://github.com/COVID19Tracking/issues/issues/773 - Does not report totals

### Historical CTP Capture does not match our understanding of what the state reports 
This could be because of the wrong test units or missing time-series

- [ ] FL https://github.com/COVID19Tracking/issues/issues/749 
    * Before 5/13 Missing `Total Tests PCR (People)` 
    * Before 5/17 Missing `Total Tests (PCR)` 
- [ ] NC https://github.com/COVID19Tracking/issues/issues/772
    * On 5/17 Missing Value for `Total Tests (PCR)`
    * Before 5/11 No values for `Total Tests (PCR)`
- [x] NE https://github.com/COVID19Tracking/issues/issues/743 
    * Backfilled `Total PCR Tests (People)` through 3/27
- [ ] PR 
    * Before 5/21 Missing  `Total Tests (PCR)` [Slack Thread](https://covid-tracking.slack.com/archives/C012C4BEAR4/p1597188043264400)
- [ ] WV https://github.com/COVID19Tracking/issues/issues/769 FL reports in tests 
    * Before 4/29 Missing `Total Tests (PCR)`
- [ ] VI Reporting in unknown units
    * Before 5/13 Missing  `TotalTests (PCR)`

**Comment by muamichali** [comment]
Closing this because we are moving our tracking of these kinds of tasks to Airtable.
