### ISSUE TITLE
[PR] Backfill probable cases time-series starting on 4/24

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#829]
**State or US**: Puerto Rico

**Describe the problem**
CTP did not separately capture what they report as probable cases, though we do lump that number with the confirmed to make the Positive Cases (People, confirmed + probable)  number.

**Action Plan**

- [x] Backfill` Probable Cases` from 4/29-now from `Positive Antibody Tests`
- [x] Update Positive Cases (PCR) on 5/18 to 1195 from 2710
- [x] Backfill `Probable Cases` & `Positive Antibody Tests` from 4/24-4/28 from total-confirmed

**Link to data source**
https://covidtracking.com/screenshots/PR/PR-secondary-20200424-181629.png
https://covidtracking.com/screenshots/PR/PR-secondary-20200518-184759.png

**Previous Issue**
https://github.com/COVID19Tracking/issues/issues/703
