### ISSUE TITLE
[GU] Back-fill Probable Cases and Positive Cases (PCR) from screenshots

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#832]
**State or US**: Guam

**Describe the problem**
Guam started to separate reporting of probable and confirmed cases on 4/19. 
CTP capture of Positive Cases (PCR) started on 4/29. 
CTP capture of Probable cases started on 7/28.

**Action Plan**
- [ ] Backfill Positive Cases PCR  from 4/19 - 4/28 using screenshots
- [ ] Backfill probable cases from 4/19 - 7/28 using` { Positive - Positive Cases PCR}` (spot check screenshots)
- [ ] Slightly amend total cases on 4/23, 4/24, 4/27 and 4/28 based on screenshots

**Link to data source**
[Guam Screenshots on CovidTracking.com](https://covidtracking.com/data/state/guam/screenshots)

**Comment by muamichali** [comment]
Before and After data is in the attached spreadsheet
[Guam Probable Timeseries Backfill.xlsx](https://github.com/COVID19Tracking/issues/files/5226550/Guam.Probable.Timeseries.Backfill.xlsx)
